apiVersion: v1
kind: Secret

metadata: 
  name: db-connection
type: Opaque

data:
  db_user: cG9zdGdyZXM=
  db_password: cG9zdGdyZXM=
  db_host: cG9zdGdyZXM=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=