name: CI
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Builds and push'
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t rodrigomolter/nlw-journey:latest .